/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import java.util.Arrays;

/**
 *
 * @author Rafael
 */
public class VistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogin
     */
    
    private String contrasena;
    private String confirmarContrasena;
    private String usuario;
   
    public VistaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonNuevoUsuario = new javax.swing.JButton();
        fieldUsuario = new javax.swing.JTextField();
        fieldContrasena = new javax.swing.JPasswordField();
        botonEntrar = new javax.swing.JButton();
        botonConfirmar = new javax.swing.JButton();
        botonConfirmar.setVisible(false);
        labelNombreUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        labelConfirmarContrasena = new javax.swing.JLabel();
        labelConfirmarContrasena.setVisible(false);
        fieldConfirmacionContrasena = new javax.swing.JPasswordField();
        fieldConfirmacionContrasena.setVisible(false);
        usuarioCreado = new javax.swing.JLabel();
        usuarioCreado.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botonNuevoUsuario.setText("Crear nuevo usuario");
        botonNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoUsuarioActionPerformed(evt);
            }
        });

        fieldUsuario.setText("Usuario");
        fieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsuarioActionPerformed(evt);
            }
        });

        fieldContrasena.setText("Contrasena");

        botonEntrar.setText("Entrar");
        botonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });

        botonConfirmar.setText("Crear Usuario");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        labelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        labelNombreUsuario.setText("Nombre de Usuario");

        labelContrasena.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        labelContrasena.setText("Contraseña");

        labelConfirmarContrasena.setText("Confirmar Contraseña");

        fieldConfirmacionContrasena.setText("Contrasena");

        usuarioCreado.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        usuarioCreado.setText("Usuario ha sido creado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNombreUsuario)
                    .addComponent(labelContrasena)
                    .addComponent(labelConfirmarContrasena)
                    .addComponent(botonNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldConfirmacionContrasena, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldContrasena, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usuarioCreado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreUsuario)
                .addGap(5, 5, 5)
                .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(labelConfirmarContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldConfirmacionContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioCreado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(botonNuevoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEntrar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        botonConfirmar.setVisible(true);
        botonEntrar.setVisible(false);
        botonNuevoUsuario.setVisible(false);
        fieldConfirmacionContrasena.setVisible(true);
        labelConfirmarContrasena.setVisible(true);
        usuarioCreado.setVisible(false);
        
    }//GEN-LAST:event_botonNuevoUsuarioActionPerformed

    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed

        //System.out.println(usuario);
        
    }//GEN-LAST:event_botonEntrarActionPerformed

    public void agregarListeners(ActionListener accion){
        this.botonConfirmar.addActionListener(accion);
        this.botonConfirmar.setActionCommand("crearUsuario");
        this.botonEntrar.addActionListener(accion);
        this.botonEntrar.setActionCommand("loguearUsuario");
    }
    
    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        // TODO add your handling code here:
        botonConfirmar.setVisible(false);
        botonEntrar.setVisible(true);
        botonNuevoUsuario.setVisible(true);
        fieldConfirmacionContrasena.setVisible(false);
        labelConfirmarContrasena.setVisible(false);
        

    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void fieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsuarioActionPerformed

    public String getContrasena(){
        return this.contrasena;
    }
    public String getContrasenaConfirmada(){
        return this.confirmarContrasena;
    }
    public String getUsuario(){
        return this.usuario;
    }
    public void usuarioCreado(){
        //this.usuarioCreado
    }
    
    public void guardarUsuarioContrasenaEnObjeto(){
        usuario = fieldUsuario.getText();
        contrasena = new String(fieldContrasena.getPassword());
        confirmarContrasena = new String(fieldConfirmacionContrasena.getPassword());        
    }
    
    
    public void limpiar(){
        this.contrasena = "";
        this.confirmarContrasena = "";
        this.usuario = "";
        this.fieldConfirmacionContrasena.setText("");
        this.fieldContrasena.setText("");
        this.fieldUsuario.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton botonEntrar;
    private javax.swing.JButton botonNuevoUsuario;
    private javax.swing.JPasswordField fieldConfirmacionContrasena;
    private javax.swing.JPasswordField fieldContrasena;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel labelConfirmarContrasena;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JLabel usuarioCreado;
    // End of variables declaration//GEN-END:variables
}
