/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Pokemon;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author fcuevas
 */
public class VistaBatalla extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public VistaBatalla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Capa2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Capa1 = new javax.swing.JLayeredPane();
        texto = new javax.swing.JLabel();
        btSimple = new javax.swing.JButton();
        btTriple = new javax.swing.JButton();
        btDoble = new javax.swing.JButton();
        Capa2 = new javax.swing.JLayeredPane();
        bAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        texto.setText("Seleccione tipo de combate");

        btSimple.setText("Simple");
        btSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpleActionPerformed(evt);
            }
        });

        btTriple.setText("Triple");

        btDoble.setText("Doble");
        btDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDobleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Capa1Layout = new javax.swing.GroupLayout(Capa1);
        Capa1.setLayout(Capa1Layout);
        Capa1Layout.setHorizontalGroup(
            Capa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Capa1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btSimple)
                .addGap(83, 83, 83)
                .addComponent(btDoble)
                .addGap(94, 94, 94)
                .addComponent(btTriple)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Capa1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(texto)
                .addGap(110, 110, 110))
        );
        Capa1Layout.setVerticalGroup(
            Capa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Capa1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(texto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(Capa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimple)
                    .addComponent(btTriple)
                    .addComponent(btDoble))
                .addGap(49, 49, 49))
        );
        Capa1.setLayer(texto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Capa1.setLayer(btSimple, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Capa1.setLayer(btTriple, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Capa1.setLayer(btDoble, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Elija su pokemon inicial");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout Capa2Layout = new javax.swing.GroupLayout(Capa2);
        Capa2.setLayout(Capa2Layout);
        Capa2Layout.setHorizontalGroup(
            Capa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Capa2Layout.createSequentialGroup()
                .addGroup(Capa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Capa2Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(bAceptar))
                    .addGroup(Capa2Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(Capa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        Capa2Layout.setVerticalGroup(
            Capa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Capa2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bAceptar)
                .addContainerGap())
        );
        Capa2.setLayer(bAceptar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Capa2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Capa2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Capa1)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Capa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(Capa1)
                    .addGap(7, 7, 7)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Capa2)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSimpleActionPerformed

    private void btDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDobleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDobleActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        
    }//GEN-LAST:event_bAceptarActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged
   public Object getValorSeleccionado(){
       return jList1.getSelectedValue();
   }
   public void agregarListener(ActionListener copucha){
        btSimple.addActionListener(copucha);
        btSimple.setActionCommand("1");
        btDoble.addActionListener(copucha);
        btDoble.setActionCommand("2");
        btTriple.addActionListener(copucha);
        btTriple.setActionCommand("3");
        bAceptar.addActionListener(copucha);
        bAceptar.setActionCommand("4");
        
                }
   public void bAceptarSegundoClick(){
       this.bAceptar.setActionCommand("5");
   }
   public void esconderCapa1(){
        this.Capa1.setVisible(false);
   }
   public void mostrarCapa2(){
        this.Capa2.setVisible(true);}
   
   public void agregarEnLista(ArrayList<Pokemon> listaPokemon){
       DefaultListModel elementosLista = new DefaultListModel();
       for(Pokemon pokemon : listaPokemon){
            elementosLista.addElement(pokemon.getNombre());
       jList1.setModel(elementosLista);
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Capa1;
    private javax.swing.JLayeredPane Capa2;
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton btDoble;
    private javax.swing.JButton btSimple;
    private javax.swing.JButton btTriple;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
