/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Pokemon;
import java.util.ArrayList;
import javax.swing.DefaultListModel;


public class VistaEquipo extends javax.swing.JDialog {

    ArrayList<ArrayList<String>> datos;
    /**
     * Creates new form VistaEquipo
     */
    public VistaEquipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        labelsEsconder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        cteLb = new javax.swing.JLabel();
        cte2Lb = new javax.swing.JLabel();
        cte3Lb = new javax.swing.JLabel();
        lbAtBase = new javax.swing.JLabel();
        lbAtMax = new javax.swing.JLabel();
        lbAeBase = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDisponibles = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cte4Lb = new javax.swing.JLabel();
        cte6Lb = new javax.swing.JLabel();
        cte7Lb = new javax.swing.JLabel();
        lbAeMax = new javax.swing.JLabel();
        lbDtBase = new javax.swing.JLabel();
        lbDtMax = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaSeleccionados = new javax.swing.JList();
        cte8Lb = new javax.swing.JLabel();
        lbDeBase = new javax.swing.JLabel();
        cte9Lb = new javax.swing.JLabel();
        lbDeMax = new javax.swing.JLabel();
        cte5Lb = new javax.swing.JLabel();
        lbHpBase = new javax.swing.JLabel();
        cte10Lb = new javax.swing.JLabel();
        lbHpMax = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cteLb.setText("Ataque Base:");

        cte2Lb.setText("Ataque Maximo:");

        cte3Lb.setText("Ataque Especial Base:");

        lbAtBase.setText("jLabel8");

        lbAtMax.setText("jLabel9");

        lbAeBase.setText("jLabel10");

        listaDisponibles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaDisponibles);

        jButton1.setText(">>");

        jButton2.setText("<<");

        btConfirmar.setText("Confirmar");

        jButton4.setText("jButton4");

        jLabel1.setText("jLabel1");

        cte4Lb.setText("Ataque Especial Max: ");

        cte6Lb.setText("Defensa Base:");

        cte7Lb.setText("Defensa Maximo:");

        lbAeMax.setText("jLabel11");

        lbDtBase.setText("jLabel12");

        lbDtMax.setText("jLabel13");

        listaSeleccionados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaSeleccionados);

        cte8Lb.setText("Defensa Especial Base:");

        lbDeBase.setText("jLabel15");

        cte9Lb.setText("Defensa Especial Max:");

        lbDeMax.setText("jLabel17");

        cte5Lb.setText("Hp Base:");

        lbHpBase.setText("jLabel3");

        cte10Lb.setText("Hp Max:");

        lbHpMax.setText("jLabel5");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(cte4Lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbAeMax))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(cte3Lb)
                                .addGap(37, 37, 37)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAtBase)
                                    .addComponent(lbAeBase)
                                    .addComponent(lbAtMax))))
                        .addGap(168, 168, 168)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cte9Lb)
                            .addComponent(cte8Lb)
                            .addComponent(cte7Lb)
                            .addComponent(cte6Lb))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDeBase)
                            .addComponent(lbDeMax)
                            .addComponent(lbDtMax)
                            .addComponent(lbDtBase))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btConfirmar)
                        .addGap(211, 211, 211)
                        .addComponent(jButton4)))
                .addGap(31, 31, 31))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cte2Lb, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cteLb, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(cte5Lb)
                .addGap(28, 28, 28)
                .addComponent(lbHpBase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cte10Lb)
                .addGap(41, 41, 41)
                .addComponent(lbHpMax)
                .addGap(67, 67, 67))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cteLb)
                            .addComponent(lbAtBase))
                        .addGap(14, 14, 14)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cte2Lb)
                            .addComponent(lbAtMax)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cte6Lb)
                            .addComponent(lbDtBase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cte7Lb)
                            .addComponent(lbDtMax))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cte3Lb)
                    .addComponent(lbAeBase)
                    .addComponent(cte8Lb)
                    .addComponent(lbDeBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cte4Lb)
                    .addComponent(lbAeMax)
                    .addComponent(cte9Lb)
                    .addComponent(lbDeMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cte5Lb)
                    .addComponent(lbHpBase)
                    .addComponent(cte10Lb)
                    .addComponent(lbHpMax))
                .addGap(26, 26, 26)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar)
                    .addComponent(jButton4))
                .addContainerGap())
        );
        jLayeredPane1.setLayer(cteLb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cte2Lb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cte3Lb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbAtBase, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbAtMax, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbAeBase, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btConfirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cte4Lb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cte6Lb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cte7Lb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbAeMax, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbDtBase, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbDtMax, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cte8Lb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbDeBase, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cte9Lb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbDeMax, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cte5Lb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbHpBase, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cte10Lb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbHpMax, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDatos(ArrayList<ArrayList<String>> datos){
        this.datos = datos;
        this.agregarEnLista(this.datos);
        // ORDEN DEL STRING: POKEDEX, NOMBREFAMILIA,AtBase,AtMax,DfBase,DfMax,AeBase,AeMax,DeBase,DeMax,HpBase,HpMax
        
    }
    public void agregarEnLista(ArrayList<ArrayList<String>> listaPokemon){
            
       
    DefaultListModel elementosLista = new DefaultListModel();
        for(ArrayList<String> pokemonysusdatos : listaPokemon){
            elementosLista.addElement(pokemonysusdatos.get(1));
        listaDisponibles.setModel(elementosLista);
       
              
       }
        
       
   }
    public void labelsEsconder(){
        this.cteLb.setVisible(false);
        this.cte2Lb.setVisible(false);
        this.cte3Lb.setVisible(false);
        this.cte4Lb.setVisible(false);
        this.cte5Lb.setVisible(false);
        this.cte6Lb.setVisible(false);
        this.cte7Lb.setVisible(false);
        this.cte8Lb.setVisible(false);
        this.cte9Lb.setVisible(false);
        this.cte10Lb.setVisible(false);
        
        
        
    }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaEquipo dialog = new VistaEquipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    
        
    
        
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JLabel cte10Lb;
    private javax.swing.JLabel cte2Lb;
    private javax.swing.JLabel cte3Lb;
    private javax.swing.JLabel cte4Lb;
    private javax.swing.JLabel cte5Lb;
    private javax.swing.JLabel cte6Lb;
    private javax.swing.JLabel cte7Lb;
    private javax.swing.JLabel cte8Lb;
    private javax.swing.JLabel cte9Lb;
    private javax.swing.JLabel cteLb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAeBase;
    private javax.swing.JLabel lbAeMax;
    private javax.swing.JLabel lbAtBase;
    private javax.swing.JLabel lbAtMax;
    private javax.swing.JLabel lbDeBase;
    private javax.swing.JLabel lbDeMax;
    private javax.swing.JLabel lbDtBase;
    private javax.swing.JLabel lbDtMax;
    private javax.swing.JLabel lbHpBase;
    private javax.swing.JLabel lbHpMax;
    private javax.swing.JList listaDisponibles;
    private javax.swing.JList listaSeleccionados;
    // End of variables declaration//GEN-END:variables
}
