/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class VistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogin
     */
    
    private String contrasena;
    private String confirmarContrasena;
    private String usuario;
   
    public VistaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonNuevoUsuario = new javax.swing.JButton();
        fieldUsuario = new javax.swing.JTextField();
        fieldContrasena = new javax.swing.JPasswordField();
        botonEntrar = new javax.swing.JButton();
        botonConfirmar = new javax.swing.JButton();
        botonConfirmar.setVisible(false);
        labelNombreUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        labelConfirmarContrasena = new javax.swing.JLabel();
        labelConfirmarContrasena.setVisible(false);
        fieldConfirmacionContrasena = new javax.swing.JPasswordField();
        fieldConfirmacionContrasena.setVisible(false);
        botonAtras = new javax.swing.JButton();
        botonAtras.setVisible(false);
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botonNuevoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        botonNuevoUsuario.setText("Crear nuevo usuario");
        botonNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoUsuarioActionPerformed(evt);
            }
        });

        fieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        fieldUsuario.setText("Usuario");
        fieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsuarioActionPerformed(evt);
            }
        });

        fieldContrasena.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        fieldContrasena.setText("Contrasena");

        botonEntrar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        botonEntrar.setText("Entrar");
        botonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });

        botonConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        botonConfirmar.setText("Crear Usuario");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        labelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        labelNombreUsuario.setText("Nombre de Usuario");

        labelContrasena.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        labelContrasena.setText("Contraseña");

        labelConfirmarContrasena.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        labelConfirmarContrasena.setText("Confirmar Contraseña");

        fieldConfirmacionContrasena.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        fieldConfirmacionContrasena.setText("Contrasena");

        botonAtras.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(botonConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldConfirmacionContrasena, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldContrasena, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelContrasena, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelConfirmarContrasena, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelNombreUsuario)
                .addGap(5, 5, 5)
                .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(labelConfirmarContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldConfirmacionContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(botonConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNuevoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEntrar)
                .addGap(18, 18, 18)
                .addComponent(botonAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        botonConfirmar.setVisible(true);
        botonEntrar.setVisible(false);
        botonNuevoUsuario.setVisible(false);
        botonAtras.setVisible(true);
        botonSalir.setVisible(false);
        fieldConfirmacionContrasena.setVisible(true);
        labelConfirmarContrasena.setVisible(true);
        
    }//GEN-LAST:event_botonNuevoUsuarioActionPerformed

    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed

        //System.out.println(usuario);
        
    }//GEN-LAST:event_botonEntrarActionPerformed

    public void agregarListeners(ActionListener accion){
        this.botonConfirmar.addActionListener(accion);
        this.botonConfirmar.setActionCommand("crearUsuario");
        this.botonEntrar.addActionListener(accion);
        this.botonEntrar.setActionCommand("loguearUsuario");
    }
    
    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        // TODO add your handling code here:
        botonConfirmar.setVisible(false);
        botonEntrar.setVisible(true);
        botonNuevoUsuario.setVisible(true);
        botonAtras.setVisible(false);
        botonSalir.setVisible(true);
        fieldConfirmacionContrasena.setVisible(false);
        labelConfirmarContrasena.setVisible(false);     
        
    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void fieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsuarioActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        botonConfirmar.setVisible(false);
        botonEntrar.setVisible(true);
        botonNuevoUsuario.setVisible(true);
        botonAtras.setVisible(false);
        botonSalir.setVisible(true);
        fieldConfirmacionContrasena.setVisible(false);
        labelConfirmarContrasena.setVisible(false);
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    public String getContrasena(){
        return this.contrasena;
    }
    public String getContrasenaConfirmada(){
        return this.confirmarContrasena;
    }
    public String getUsuario(){
        return this.usuario;
    }
    public void usuarioCreado(){
        //this.usuarioCreado
    }
    
    public void guardarUsuarioContrasenaEnObjeto(){
        usuario = fieldUsuario.getText();
        contrasena = new String(fieldContrasena.getPassword());
        confirmarContrasena = new String(fieldConfirmacionContrasena.getPassword());        
    }    
    
    public void limpiar(){
        this.contrasena = "";
        this.confirmarContrasena = "";
        this.usuario = "";
        this.fieldConfirmacionContrasena.setText("");
        this.fieldContrasena.setText("");
        this.fieldUsuario.setText("");
    }

    public void mostrarVentanaEmergente(int caso){
        switch(caso){
            case 0:
                JOptionPane.showMessageDialog(this, "Bienvenido, "+usuario);
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "El nuevo usuario se ha creado satisfactoriamente");
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "El nombre de usuario y/o contraseña son erroneos");
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe");
                break;
            case 4:
                JOptionPane.showMessageDialog(this, "Las contraseñas son diferentes");
                break;
            case 5:
                JOptionPane.showMessageDialog(this, "Ingrese una contraseña");
                break;
            case 6:
                JOptionPane.showMessageDialog(this, "Ingrese un nombre de usuario");
                break;
            case 7:
                JOptionPane.showMessageDialog(this, "Conexion con la base de datos a fallado");
                break;
            default:
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error desconocido");
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton botonEntrar;
    private javax.swing.JButton botonNuevoUsuario;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPasswordField fieldConfirmacionContrasena;
    private javax.swing.JPasswordField fieldContrasena;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel labelConfirmarContrasena;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
